### ISSUE TITLE
Extension Roadmap

### ISSUE THREAD

**Issue by Spence-S** [xojs/vscode-linter-xo#95]
As it stands, the xo linter extension works fairly well but is pretty bare bones and needs some fixing up. 

current extension:
https://marketplace.visualstudio.com/items?itemName=samverschueren.linter-xo

### Immediate goals
- [x] publish v3 under SamVerschueren.linter-xo 
    - Can now be used immediately under the soon to be deprecated [spence-s.linter-xo](https://marketplace.visualstudio.com/items?itemName=spence-s.linter-xo) extension - this adds support for xo versions 40+ and new features are being rolled out while maintenance changes hands.
    - deprecate installs of spence-s.linter-xo and show message on start up for users to migrate back to SamVerschuren.linter-xo
- [x] support multi root workspaces correctly
- [x] remove any reliance on package.json fields and instead attempt to resolve the library relative to the working folder, and only then error 
- [x] enable the extension by default 
- [x] ~add a couple of simple commands to restart and run the extension as requested~ Now recaches xo after updating on the next file open.
- [x] Configurable debounce which improves large file linting performance
- [x] Code Action quick fixes are now available 
- [ ] Support format on save "modifications" mode.
- [ ] Add tests for the extension, CI, automated releases
- [ ] Support code action fix all commands 
- [x] Code action ignore rule quick fixes
- [x] Add optional rule documentation links

**Comment by tusbar** [comment]
Wouldn't be a bad thing to request migrating this repo to the XO (https://github.com/xojs) organization.

**Comment by Spence-S** [comment]
@tusbar I'd like to do that, however, I am only a collaborator on a user repository here - so I don't believe there is anything I can do. @SamVerschueren Would you be ok to work with @sindresorhus to move this to the xo org? - It would be nice to have a few more permissions that I don't think I can get as a collaborator on a user repo. For instance, I'd like to make issue templates to suggest common debugging steps and currently don't believe I can do.

**Comment by SamVerschueren** [comment]
I'm ok with moving it. @sindresorhus what do you think?

**Comment by darkred** [comment]
> It would be nice to have a few more permissions that I don't think I can get as a collaborator on a user repo. For instance, I'd like to make issue templates to suggest common debugging steps and currently don't believe I can do.

@Spence-S 
I think what you need is the repo to be *transferred* to you, not be just a collaborator.
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by sindresorhus** [comment]
@SamVerschueren 👍

**Comment by yakov116** [comment]
@Spence-S can you clean up all the issues?

**Comment by tusbar** [comment]
@Spence-S is anything blocking the release process? Can we help in any way? I’d like to start updating xo on my repos and don’t want to ask people to switch to your fork.

**Comment by SamVerschueren** [comment]
I'm in contact with the VSC team to add @Spence-S as contributor but for some reason what they did didn't work. So we're trying to resolve it. Sorry for the inconvenience.

**Comment by sindresorhus** [comment]
@SamVerschueren I think you should have access to move the repo to the organization. And if not, just move it to me and I'll move it to the organization.

**Comment by SamVerschueren** [comment]
Oh yes. I'll try to do it this evening. But I think the question was for releasing it in the marketplace.

**Comment by Spence-S** [comment]
The VScode team has resolved publishing issues and I have released the extension updates under the original https://marketplace.visualstudio.com/items?itemName=samverschueren.linter-xo

**Comment by Spence-S** [comment]
Closing this road map as most of the goals have been met now. Will make individual issues for new features going forward.
